import { WorkflowNode, WorkflowEdge } from "./types";

export const templates: Record<string, { nodes: WorkflowNode[]; edges: WorkflowEdge[] }> = {
  vat: {
    nodes: [
      {
        id: "node-1",
        name: "Daily Invoices Received",
        nameAr: "استقبال الفواتير اليومية",
        desc: "Launches when daily sales invoices are pulled from ERP",
        descAr: "يسحب فواتير المبيعات والمشتريات من دفاتر الأستاذ يومياً",
        type: "trigger",
        iconName: "Blocks",
        x: 80,
        y: 220,
        status: "idle",
        config: { triggerEvent: "Daily Scheduled Pull", apiEndpoint: "/api/accounting/ledger" },
        inputPayload: { schedule: "daily", pullTime: "02:00 UTC", count: 12 },
        outputPayload: { transactionsFound: 12, currency: "SAR", sum: 825120 },
      },
      {
        id: "node-2",
        name: "Verify Calculations",
        nameAr: "تدقيق الحسابات الرياضية",
        desc: "Validates subtotal * 15% matches recorded tax",
        descAr: "يطابق الفواتير حسابياً للتحقق من سلامة نسبة الـ 15%",
        type: "action",
        iconName: "FileText",
        x: 320,
        y: 220,
        status: "idle",
        config: { apiEndpoint: "/api/workflows/run-step", authMethod: "Bearer Token" },
        inputPayload: { transactionsFound: 12 },
        outputPayload: { successCount: 11, errorCount: 1, mismatchInvoice: "ST-8812" },
      },
      {
        id: "node-3",
        name: "ZATCA Compliance Guard",
        nameAr: "فحص متطلبات هيئة ZATCA",
        desc: "Validates 15-digit VAT number & digital stamp",
        descAr: "يتحقق من هيكل الرقم الضريبي والأكواد والاشتراطات",
        type: "action",
        iconName: "ShieldAlert",
        x: 560,
        y: 220,
        status: "idle",
        config: { apiEndpoint: "/api/zatca/validate" },
        inputPayload: { invoices: 12 },
        outputPayload: {
          compliantCount: 10,
          criticalFlags: 2,
          nonCompliantList: ["AC-4412", "RENT-2026-02"],
        },
      },
      {
        id: "node-4",
        name: "Compliance Check Router",
        nameAr: "بوابة فحص جودة الامتثال",
        desc: "Decide pathway based on critical audit flags",
        descAr: "يوجه سير المعاملات تلقائياً بحسب وجود أخطاء امتثال",
        type: "condition",
        iconName: "AlertTriangle",
        x: 800,
        y: 220,
        status: "idle",
        config: { conditionField: "criticalFlags", conditionOperator: "===", conditionValue: "0" },
        inputPayload: { criticalFlags: 2 },
        outputPayload: { conditionMet: false, routeTaken: "False Branch" },
      },
      {
        id: "node-5",
        name: "Submit approved Form 50",
        nameAr: "تقديم الإقرار التلقائي (Form 50)",
        desc: "Submits qualified records directly to ZATCA integration endpoint",
        descAr: "يربط ويرسل الإقرارات السليمة لبوابة مصلحة الضرائب والجمارك",
        type: "action",
        iconName: "Send",
        x: 1040,
        y: 100,
        status: "idle",
        config: { apiEndpoint: "https://api.zatca.gov.sa/v2/returns" },
        inputPayload: { form50: { sales: 565000, tax: 84750 } },
        outputPayload: { referenceCode: "ZATCA-SUB-881273", timestamp: "2026-07-11 05:40:12" },
      },
      {
        id: "node-6",
        name: "Alert Tax Manager",
        nameAr: "إشعار طارئ لمدير الامتثال",
        desc: "Sends instant notification of non-compliance issues via system & email",
        descAr: "ينبه مدير الضرائب فوراً بوجود أخطاء بالفواتير والروابط",
        type: "action",
        iconName: "Mail",
        x: 1040,
        y: 340,
        status: "idle",
        config: {
          recipientEmail: "moemahran@gmail.com",
          promptTemplate: "رصدت بوابة مدارج أخطاء امتثال حرجة في فحص ZATCA للمستندات.",
        },
        inputPayload: { recipient: "moemahran@gmail.com", flags: ["AC-4412", "RENT-2026-02"] },
        outputPayload: { sent: true, notificationId: "NOTIF-9912", transport: "SMTP" },
      },
    ],
    edges: [
      { from: "node-1", to: "node-2" },
      { from: "node-2", to: "node-3" },
      { from: "node-3", to: "node-4" },
      { from: "node-4", to: "node-5" },
      { from: "node-4", to: "node-6" },
    ],
  },
  audit: {
    nodes: [
      {
        id: "node-1",
        name: "Bank Statement Received",
        nameAr: "استقبال كشف الحساب البنكي",
        desc: "Triggers on daily MT940 / CSV statements uploaded",
        descAr: "تنشيط المسار فور رفع كشوف الحركات البنكية لشركة مدارج",
        type: "trigger",
        iconName: "Database",
        x: 80,
        y: 220,
        status: "idle",
        config: { triggerEvent: "On File Upload", webhookUrl: "/api/audit/bank-statement" },
        inputPayload: { fileName: "SA_ALRAJHI_JUNE.csv", entries: 9 },
        outputPayload: { receivedEntries: 9, period: "June 2026" },
      },
      {
        id: "node-2",
        name: "AI Ledger Categorization",
        nameAr: "التصنيف التلقائي بالذكاء الاصطناعي",
        desc: "Uses Gemini-3.5-flash to intelligently categorize ledger lines",
        descAr: "تصنيف وتحليل البنود البنكية وفرز المصاريف بأكواد ذكية",
        type: "action",
        iconName: "Cpu",
        x: 320,
        y: 220,
        status: "idle",
        config: {
          selectedModel: "gemini-3.5-flash",
          promptTemplate: "صنف المصروفات والمدفوعات البنكية بناءً على قيود شركة مدارج...",
        },
        inputPayload: { entries: 9 },
        outputPayload: {
          categorized: 9,
          categories: ["أصول", "صيانة", "إيجار", "مبيعات", "نثريات"],
        },
      },
      {
        id: "node-3",
        name: "Detect Missing Receipts",
        nameAr: "رصد المستندات المفقودة",
        desc: "Scans bank ledger for transactions without a corresponding invoice",
        descAr: "مقارنة الحركات البنكية مع الفواتير المرفوعة لكشف فجوات الفحص",
        type: "action",
        iconName: "AlertTriangle",
        x: 560,
        y: 220,
        status: "idle",
        config: { apiEndpoint: "/api/workflows/run-step" },
        inputPayload: { bankLedgerCount: 9, invoiceCount: 10 },
        outputPayload: { matched: 7, missingReceiptsCount: 2, totalUnvouchedAmount: 4700 },
      },
      {
        id: "node-4",
        name: "Balance Threshold Router",
        nameAr: "بوابة قيمة العجز المالي",
        desc: "Routes workflow if total unvouched amount exceeds limits",
        descAr: "فحص حجم المبالغ المفقودة مستنداتها لتوجيه مسار التسويات",
        type: "condition",
        iconName: "Sliders",
        x: 800,
        y: 220,
        status: "idle",
        config: {
          conditionField: "totalUnvouchedAmount",
          conditionOperator: ">",
          conditionValue: "1000",
        },
        inputPayload: { totalUnvouchedAmount: 4700 },
        outputPayload: { conditionMet: true, routeTaken: "True Branch" },
      },
      {
        id: "node-5",
        name: "Generate qualified SOCPA pack",
        nameAr: "تجهيز حزمة المراجعة والتحفظ",
        desc: "Compiles qualified audit report detailing the unvouched expenses",
        descAr: "توليد تقرير التدقيق النهائي مع إدراج ملاحظات التحفظ القانونية",
        type: "action",
        iconName: "FileText",
        x: 1040,
        y: 100,
        status: "idle",
        config: { apiEndpoint: "/api/audit/generate-report" },
        inputPayload: { clientName: "شركة مدارج النموذجية", qualified: true },
        outputPayload: {
          opinion: "Qualified (تحفظي)",
          financialMetrics: { revenue: 565000, directCosts: 184000 },
        },
      },
      {
        id: "node-6",
        name: "Auto-Reconcile Clean Assets",
        nameAr: "التسوية التلقائية والترحيل",
        desc: "Directly reconciles matched logs to main ERP",
        descAr: "ترحيل قيود النقدية السليمة لدفاتر المحاسبة العامة بـ ERP",
        type: "action",
        iconName: "CheckCircle2",
        x: 1040,
        y: 340,
        status: "idle",
        config: { apiEndpoint: "/api/accounting/reconcile" },
        inputPayload: { countToReconcile: 7 },
        outputPayload: { reconciled: true, ledgerStatus: "Balanced" },
      },
    ],
    edges: [
      { from: "node-1", to: "node-2" },
      { from: "node-2", to: "node-3" },
      { from: "node-3", to: "node-4" },
      { from: "node-4", to: "node-5" },
      { from: "node-4", to: "node-6" },
    ],
  },
  negotiation: {
    nodes: [
      {
        id: "node-1",
        name: "Milestone Accomplished",
        nameAr: "حافز إنجاز مرحلة عقدية",
        desc: "Triggers on contractor task completion submissions",
        descAr: "يتم تفعيله فور تأكيد المقاول انتهاء أعمال وتسليم مرحلة من العقد",
        type: "trigger",
        iconName: "Play",
        x: 80,
        y: 220,
        status: "idle",
        config: { triggerEvent: "On Task Completion", apiEndpoint: "/api/projects/tasks" },
        inputPayload: {
          taskId: "TSK-8812",
          milestoneName: "تأسيس البنية التقنية السحابية",
          contractId: "MDR-2026-CTR9",
        },
        outputPayload: {
          contractId: "MDR-2026-CTR9",
          milestoneName: "تأسيس البنية التقنية السحابية",
          status: "In_Review",
        },
      },
      {
        id: "node-2",
        name: "Inspect Sign-off Reports",
        nameAr: "فحص مستندات وإيصالات المرحلة",
        desc: "Ensures technical consultant sign-off logs are present",
        descAr: "يراجع تقارير الاستشاري المعتمد ووثائق الفحص القانونية للمرحلة",
        type: "action",
        iconName: "FileText",
        x: 320,
        y: 220,
        status: "idle",
        config: { apiEndpoint: "/api/negotiations/verify-docs" },
        inputPayload: { taskId: "TSK-8812" },
        outputPayload: { isSignedOff: true, findings: "All documents successfully verified." },
      },
      {
        id: "node-3",
        name: "Arbitration Board Approval",
        nameAr: "موافقة مستشار الامتثال القانوني",
        desc: "Verifies dispute-free sign-off from compliance lawyers",
        descAr: "تأكيد سلامة البنود وخلو المطالبات من أي نزاعات معلقة",
        type: "action",
        iconName: "UserCheck",
        x: 560,
        y: 220,
        status: "idle",
        config: { apiEndpoint: "/api/negotiations/dispute-check" },
        inputPayload: { contractId: "MDR-2026-CTR9" },
        outputPayload: { hasActiveDisputes: false, approvedByLegal: true },
      },
      {
        id: "node-4",
        name: "Dispute Filter Router",
        nameAr: "بوابة خلو النزاعات العقدية",
        desc: "Routes workflow to release funds or flag mediation",
        descAr: "بوابة توجيه خط السداد بناءً على تقييم المخاطر القانونية",
        type: "condition",
        iconName: "AlertTriangle",
        x: 800,
        y: 220,
        status: "idle",
        config: {
          conditionField: "approvedByLegal",
          conditionOperator: "===",
          conditionValue: "true",
        },
        inputPayload: { approvedByLegal: true },
        outputPayload: { conditionMet: true, routeTaken: "True Branch" },
      },
      {
        id: "node-5",
        name: "Release Escrow Banking API",
        nameAr: "صرف المبالغ المضمونة (Escrow)",
        desc: "Directs Banking gateway API to release held contractor milestone funds",
        descAr: "تشغيل ربط البنك آلياً للإفراج عن قيمة الدفعة من حساب الضمان",
        type: "action",
        iconName: "Zap",
        x: 1040,
        y: 100,
        status: "idle",
        config: { apiEndpoint: "https://api.alrajhibank.com.sa/escrow/release" },
        inputPayload: { escrowId: "ESC-88129B", releaseAmount: 75000 },
        outputPayload: { transferReceipt: "TX-BANK-88219B", transferStatus: "Settled" },
      },
      {
        id: "node-6",
        name: "Alert Arbitration Panel",
        nameAr: "إحالة النزاع للتحكيم والوساطة",
        desc: "Triggers task routing to mediate contract parameters manually",
        descAr: "توجيه الملف للجنة المراجعة والتحكيم مع تجميد مبالغ الضمان",
        type: "action",
        iconName: "Clock",
        x: 1040,
        y: 340,
        status: "idle",
        config: { apiEndpoint: "/api/negotiations/arbitrate" },
        inputPayload: { contractId: "MDR-2026-CTR9" },
        outputPayload: { arbitrationCaseId: "CASE-9912", caseStatus: "Opened" },
      },
    ],
    edges: [
      { from: "node-1", to: "node-2" },
      { from: "node-2", to: "node-3" },
      { from: "node-3", to: "node-4" },
      { from: "node-4", to: "node-5" },
      { from: "node-4", to: "node-6" },
    ],
  },
};
